services:
  storage-client:
    # build: .
    image: ixcdevops/storage-client:2.0.5-threadpool
    container_name: storage-client
    # ports:
    #   - "8080:5000"
    volumes:
      - /media/SSD-Storage/OneDrive:/data
    environment:
      - AZURE_STORAGE_ACCOUNT_KEY=
      - AZURE_STORAGE_ACCOUNT_NAME=
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_PATH=/data
      - ONEDRIVE_CLIENT_ID=
      - ONEDRIVE_CLIENT_SECRET=
      - ONEDRIVE_REDIRECT_URI=https://zimaos.local/storage/onedrive/callback
      - SECRET_KEY=
    depends_on:
      - redis
    restart: unless-stopped

  celery-worker:
    # build: .
    image: ixcdevops/storage-client:2.0.5-threadpool
    container_name: storage-celery
    command: celery -A run.celery_app worker --loglevel=info --concurrency=4
    volumes:
      - /media/SSD-Storage/OneDrive:/data
    environment:
      - AZURE_STORAGE_ACCOUNT_KEY=
      - AZURE_STORAGE_ACCOUNT_NAME=
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DOWNLOAD_PATH=/data
      - ONEDRIVE_CLIENT_ID=
      - ONEDRIVE_CLIENT_SECRET=
      - ONEDRIVE_REDIRECT_URI=https://zimaos.local/storage/onedrive/callback
      - SECRET_KEY=
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: storage-redis
    restart: unless-stopped

  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - storage-client
    volumes:
      - ./nginx:/etc/nginx
      - ./certs:/etc/letsencrypt
